services:
  db:
    image: postgres:16
    container_name: jobtracker_db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build: ./server
    env_file:
      - .env
    container_name: jobtracker_backend
    depends_on:
      - db
    environment:
      DATABASE_HOSTNAME: ${DATABASE_HOSTNAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    ports:
      - "8000:8000"

  frontend:
    build: ./web
    env_file:
      - .env
    container_name: jobtracker_frontend
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  postgres_data: