from enum import Enum


class AssessmentType(str, Enum):
    ONLINE_ASSESSMENT = "ONLINE_ASSESSMENT"
    INTERVIEW = "INTERVIEW"
    ASSESSMENT_CENTRE = "ASSESSMENT_CENTRE"


class ApplicationStatus(str, Enum):
    NOT_APPLIED = "NOT_APPLIED"
    APPLIED = "APPLIED"
    INTERVIEW = "INTERVIEW"
    REJECTED = "REJECTED"
    SUCCESSFUL = "SUCCESSFUL"

